$(document).ready ->
  roleSearch = (query, syncResults, asyncResults) ->
    $.get '/roles.json', { query: query }, ((data) ->
      asyncResults data
      return
    ), 'json'
    return

  $('.autocomplete_role').typeahead {
    minLength: 0
    hint: false
    highlight: true
  },
    name: 'autocomplete_role'
    source: roleSearch
    display: (role) ->
      role.name
  # role selected, let's set hidden role_id field
  $('.autocomplete_role').bind 'typeahead:select', (ev, role) ->
    # Set hidden form field of role_id
    $('.autocomplete_role_id').val role.id
    return
  return

# ---
# generated by js2coffee 2.2.0