$(document).ready ->
  locationSearch = (query, syncResults, asyncResults) ->
    $.get '/locations.json', { query: query }, ((data) ->
      asyncResults data
      return
    ), 'json'
    return

  $('.autocomplete_location').typeahead {
    minLength: 1
    hint: false
    highlight: true
  },
    name: 'autocomplete_location'
    source: locationSearch
    display: (location) ->
      location.display_name
  # location selected, let's set hidden location_id field
  $('.autocomplete_location').bind 'typeahead:select', (ev, location) ->
    # Set hidden form field of location_id
    $('.autocomplete_location_id').val location.id
    return
  return

# ---
# generated by js2coffee 2.2.0