$(document).ready ->
  companySearch = (query, syncResults, asyncResults) ->
    $.get '/companies', { query: query }, ((data) ->
      asyncResults data
      cacheCompanies data
      return
    ), 'json'
    return

  cacheCompanies = (data) ->
    if !window.__companiesCache
      window.__companiesCache = {}
    i = 0
    while i < data.length
      company = data[i]
      window.__companiesCache[company.name] = company
      i++
    return

  isCompanyCached = (name) ->
    if window.__companiesCache[name] == undefined
      return false
    true


  $('.autocomplete_company').typeahead {
    minLength: 1
    hint: false
    highlight: true
  },
    name: 'autocomplete_company'
    source: companySearch
    display: (company) ->
      company.name
    templates:
      suggestion: (el) ->
        '<div>' + '<img class="mr-2 rounded" width="50" src="' + el.avatar_url + '" />' + '<strong>' + el.name + '</strong> ' + '</div>'
  # company selected, let's set hidden company_id field
  $('.autocomplete_company').bind 'typeahead:select', (ev, company) ->
    # Set hidden form field of company_id
    $('.autocomplete_company_id').val company.id
    return
  $('.autocomplete_company').bind 'blur', (ev) ->
    # clear company id if no value
    company = ev.target.value
    if company == ""
        $('.autocomplete_company_id').val ""
    else
      cached = isCompanyCached(company)
      if !cached
        $('.autocomplete_company').val ""
  return

# ---
# generated by js2coffee 2.2.0
