$(document).ready ->
 fbPageSearch = (query, syncResults, asyncResults) ->
    $.get '/company_imports/search.json', { query: query }, ((data) ->
      asyncResults data
      return
    ), 'json'
    return

  $('input#company_name').typeahead {
    minLength: 1
    hint: false
    highlight: true
  },
    name: 'fb-search-results'
    source: fbPageSearch
    display: (company) ->
      company.name
    templates:
      empty: 'not found'
      suggestion: (el) ->
        '<div>' + '<img class="mr-2 rounded" src="' + el.picture.data.url + '" />' + '<strong>' + el.name + '</strong> ' + el.link + '</div>'
  # company selected, set form value
  $('input#company_name').bind 'typeahead:select', (ev, company) ->
    $('input#company_facebook_url').val company.link
    return
  return

# ---
# generated by js2coffee 2.2.0