$(document).ready ->
  $('#new_comment').formValidation(
    framework: 'bootstrap4'
    fields:
      'comment[text]':
        validators:
          notEmpty: 
            message: 'Huh?'
  )

  return

# ---
# generated by js2coffee 2.2.0
