$(document).ready ->
  $('#new_user').formValidation(
    framework: 'bootstrap4'
    icon:
      valid: 'fa fa-check'
      invalid: 'fa fa-times'
      validating: 'fa fa-refresh'
    fields:
      'user[name]':
        validators:
          notEmpty: 
            message: 'Your full real name is required.'
      'user[email]':
        trigger: 'blur'
        validators:
          notEmpty: 
            message: 'Email is required'
          # emailAddress:
          #   message: 'Not a valid email address'
          regexp: 
            regexp: '^[^@\\s]+@([^@\\s]+\\.)+[^@\\s]+$',
            message: 'Not a valid email address'
      'user[password]': validators: 
        notEmpty: 
          message: 'Password is required'
        stringLength:
          min: 8
          message: 'Password must be at least 8 characters'
      'user[username]': validators:
        notEmpty: message: 'Username is required'
        stringLength:
          min: 1
          max: 30
          message: 'Username must be more than 1 and less than 30 characters long'
        regexp:
          regexp: /^[a-zA-Z0-9_\.-]+$/
          message: 'Username can only consist of letters, dashes, underscores or dots. '
        remote:
          message: 'Username is not available',
          url: '/users/username.json',
          delay: 300,
          name: 'q',
          validKey: 'available'

  ).on('success.validator.fv', (e, data) ->
    
    if data.field == "user[username]" && data.validator == "remote"
      hint = $('#username_hint')
      hint.text("hireclub.co/" + data.element.val())
    return
  ).on('err.validator.fv', (e, data) ->
    
    if data.field == "user[username]" && data.validator == "remote"
      hint = $('#username_hint')
      hint.text("hireclub.co/" + data.element.val())
    return
  )

  return

# ---
# generated by js2coffee 2.2.0
